---
- name: Show info about the env this host belong to
  debug:
    msg: "This host is in {{ env }} environment!!!"

- import_tasks: pre-install.yml
  tags: pre-install

- import_tasks: docker-install.yml
  tags: install
