---
- name: change user shell to bash
  user:
    name: "{{ deploy_user }}"
    shell: /bin/bash

- name: Update all packages to their latest version Debian
  apt:
    name: "*"
    state: latest
    update_cache: yes
  environment:
    - NEEDRESTART_MODE: automatically
  changed_when: false
  when: ansible_os_family == 'Debian'

- name: update all packages to their latest version RedHat
  dnf:
    name: "*"
    state: latest
  when: ansible_os_family == 'RedHat'

- name: Install depend Debian
  apt:
    name: "{{ item }}"
    state: present 
    update_cache: yes 
    install_recommends: yes
  environment:
    - NEEDRESTART_MODE: automatically
  with_items:
  - net-tools
  - curl
  - unzip
  - python3-psycopg2
  - apt-transport-https
  - ca-certificates
  - software-properties-common
  - python3-pip
  - virtualenv
  - python3-setuptools
  when: ansible_os_family == 'Debian'

- name: Install depend RedHat
  dnf:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - dnf-plugins-core
  - net-tools
  - curl
  - unzip
  - python3-psycopg2
  - ca-certificates
  - python3-pip
  - virtualenv
  - python3-setuptools
  when: ansible_os_family == 'RedHat'
